name: Workflow file for java app deployment
on:  
  workflow_dispatch:

jobs:
  job-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
  job-Build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v5
  
      - name: Java setup
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Install Maven
        run: |
            sudo apt install maven -y
            mvn --version
            mvn clean package

  job-Deploy:
   needs:   job-Build
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v5          
      - name: Download artifact
      - uses: actions/download-artifact@v5
        with:
        
          name: java-war-file
          path: ./deploy

          run: |
          tomcat_url: ${{ secrets.TOMCAT_URL}}
          tomcat_user: ${{ secrets.TOMCAT_USER}}
          tomcat_pwd: ${{secrets.TOMCAT_PASSWORD}}
      
